FROM php:7-apache
COPY php.ini /usr/local/etc/php/
RUN apt-get update && apt-get install -y \
  libfreetype6-dev libjpeg62-turbo-dev libpng12-dev libmcrypt-dev \
  git vim unzip \
  && docker-php-ext-install pdo_mysql mysqli mbstring gd iconv mcrypt \
  && apt-get clean
# install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# using composer in root
ENV COMPOSER_ALLOW_SUPERUSER=1
# create larabel project
RUN composer create-project laravel/laravel ${PROJECT_NAME} --prefer-dist
RUN cd ${PROJECT_NAME}
# RUN composer install